# Sử dụng máy chủ Nginx để chạy file HTML tĩnh
FROM nginx:alpine

# Sao chép toàn bộ file giao diện của bạn vào thư mục mặc định của Nginx
COPY . /usr/share/nginx/html

# Mở cổng 80 (cổng mặc định của web)
EXPOSE 80